name: WhatsApp Mortificaciones

on:
  schedule:
    - cron: '0 11 * * *'  # 🕗 Ejecuta todos los días a las 8 AM UTC
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run:  python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar el script
       env:
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
          CALLMEBOT_APIKEY: ${{ secrets.CALLMEBOT_APIKEY }}
        run: python mortificaciones.py  # Cambia esto si el script tiene otro nombre
